CREATE TABLE refresh_tokens
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    credential_id BIGINT NOT NULL,
    token VARCHAR(512) NOT NULL UNIQUE,
    revoked BOOLEAN NOT NULL DEFAULT FALSE,
    expires_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT fk_refresh_tokens_credentials
        FOREIGN KEY (credential_id)
            REFERENCES credentials(id)
            ON DELETE CASCADE
);