services:
  auth-service:
    container_name: auth-service
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_healthy
    build:
      context: .
      dockerfile: auth-service/Dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${AUTH_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      JWT_ACCESS_TOKEN_EXPIRATION: ${JWT_ACCESS_TOKEN_EXPIRATION}
      JWT_REFRESH_TOKEN_EXPIRATION: ${JWT_REFRESH_TOKEN_EXPIRATION}
    ports:
      - "${AUTH_SERVICE_PORT}:8087"
    networks:
      - backend-network
